<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Shops2AppsMobileAppAjax {

	function registerAjax() {
		// register ajax call on plugin page only
		if ( isset( $_POST['page'] ) && in_array( sanitize_text_field( $_POST['page'] ), Shops2AppsMobileAppConstant::$ARRAY_PLUGIN_PAGES ) ) {
			add_action( 'wp_ajax_s2a_mobile_save_configuration', array( $this, 's2a_mobile_save_configuration_callback' ) );
			add_action( 'wp_ajax_s2a_mobile_save_user', array( $this, 's2a_mobile_save_user_callback' ) );
			add_action( 'wp_ajax_s2a_mobile_save_demo_app', array( $this, 's2a_mobile_save_demo_app_callback' ) );
			add_action( 'wp_ajax_s2a_mobile_save_demo_app_status', array( $this, 's2a_mobile_save_demo_app_status_callback' ) );
			add_action( 'wp_ajax_s2a_mobile_upload_image', array( $this, 's2a_mobile_upload_image_callback' ) );
		}
	}

	function s2a_mobile_save_configuration_callback() {
		global $s2aUtil;
		$config = $s2aUtil->readConfig();

		$requestorPage = sanitize_text_field( $_POST['page'] );

		switch ( $requestorPage ) {
			case Shops2AppsMobileAppConstant::$ARRAY_PLUGIN_PAGES[0] : {
				switch ( sanitize_text_field( $_POST['tab'] ) ) {
					case 'design': {
						$config['design']['logo']                = sanitize_text_field( $_POST['logo'] );
						$config['design']['bar_color']           = sanitize_text_field( $_POST['barColor'] );
						$config['design']['home_screen_type']    = sanitize_text_field( $_POST['homeScreenType'] );
						$config['design']['home_screen_content'] = sanitize_text_field( $_POST['homeScreenContent'] );
						$config['design']['preview_ios']         = sanitize_text_field( $_POST['previewIOs'] );
						$config['design']['preview_android']     = sanitize_text_field( $_POST['previewAndroid'] );
					}
						break;
					case 'menu': {
						$config['menu']['pages'] = array();
						foreach ( $_POST['pages'] as $page ) {
							$page                      = sanitize_text_field( $page );
							$config['menu']['pages'][] = $page;
						}
					}
				}
			}
				break;
			case Shops2AppsMobileAppConstant::$ARRAY_PLUGIN_PAGES[1]: {
				switch ( sanitize_text_field( $_POST['tab'] ) ) {
					case Shops2AppsMobileAppConstant::$ARRAY_PLUGIN_PAGES_TAB[ $requestorPage ][0]: {
						$config['setting-general']['name']         = sanitize_text_field( $_POST['name'] );
						$config['setting-general']['description']  = sanitize_text_field( $_POST['description'] );
						$config['setting-general']['have_account'] = sanitize_text_field( $_POST['haveAccount'] );
					}
				}
			}
				break;
		}

		$s2aUtil->writeConfig( $config );
		wp_die();
	}

	function s2a_mobile_save_user_callback() {
		global $s2aUtil;
		$config                          = $s2aUtil->readConfig( 'conf.user.json' );
		$config['user']['email_address'] = sanitize_text_field( $_POST['emailAddress'] );
		$config['user']['api_key']       = sanitize_text_field( $_POST['apiKey'] );
		$config['user']['created_date']  = sanitize_text_field( $_POST['createdDate'] );

		$s2aUtil->writeConfig( $config, 'conf.user.json' );
		wp_die();
	}

	function s2a_mobile_save_demo_app_callback() {
		global $s2aUtil;
		$config                   = $s2aUtil->readConfig( 'conf.demo-app.json' );
		$config['demo']['id']     = sanitize_text_field( $_POST['id'] );
		$config['demo']['date']   = sanitize_text_field( $_POST['date'] );
		$config['demo']['status'] = sanitize_text_field( $_POST['status'] );

		$s2aUtil->writeConfig( $config, 'conf.demo-app.json' );
		wp_die();
	}

	function s2a_mobile_save_demo_app_status_callback() {
		global $s2aUtil;
		$config                   = $s2aUtil->readConfig( 'conf.demo-app.json' );
		$config['demo']['status'] = sanitize_text_field( $_POST['status'] );

		$config['demo']['preview'] = array();
		foreach ( $_POST['links'] as $link ) {
			$url = array();
			foreach ( $link as $data ) {
				$data  = sanitize_text_field( $data );
				$url[] = $data;
			}
			$config['demo']['preview'][] = $url;
		}

		$s2aUtil->writeConfig( $config, 'conf.demo-app.json' );
		wp_die();
	}


	function s2a_mobile_upload_image_callback() {
		$uploaded = wp_handle_upload( $_FILES['file'], array( 'test_form' => false ) );

		if ( $uploaded && ! isset( $uploaded['error'] ) ) {
			echo json_encode( array( 'isError' => 0, 'url' => $uploaded['url'] ) );
		} else {
			/**
			 * Error generated by _wp_handle_upload()
			 * @see _wp_handle_upload() in wp-admin/includes/file.php
			 */
			echo json_encode( array( 'isError' => 1, 'message' => $uploaded['error'] ) );
		}
		wp_die();
	}
}